# Generated by Django 5.1 on 2025-11-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.CharField(max_length=100)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=250, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('id_reseña', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app_Spa.pedidos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='app_Spa.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_Spa.usuarios'),
        ),
    ]
